# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16G22jvJdAvXUjyLHq9b6oVQ6wQLOu0g8
"""

# prompt: import streamlit as st
# import pickle
# import numpy as np
# # Load the saved model
# model = pickle.load(open('linear_reg.sav', 'rb'))
# st.title('Sales Prediction App')
# # Input features
# TV = st.number_input('TV Advertising Budget', min_value=0.0)
# Radio = st.number_input('Radio Advertising Budget', min_value=0.0)
# Newspaper = st.number_input('Newspaper Advertising Budget', min_value=0.0)
# # Make prediction
# if st.button('Predict Sales'):
#     input_data = np.array([[TV, Radio, Newspaper]])
#     prediction = model.predict(input_data)[0]
#     st.success(f'Predicted Sales: {prediction:.2f}')
#  UPDATE THIS MODEL WITH     from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import r2_score, mean_squared_error
# import statsmodels.api as sm
# # Define features (X) and target variable (y)
# X = df[['Income', 'Age', 'Education_Level', 'Monthly_Purchases']]  # Example features, you can modify
# y = df['Spending_Score']
# # Split data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# # Initialize and train the linear regression model
# model = LinearRegression()
# model.fit(X_train, y_train)
# # Make predictions on the test set
# y_pred = model.predict(X_test)
# # Evaluate the model
# r2 = r2_score(y_test, y_pred)
# mse = mean_squared_error(y_test, y_pred)
# print(f"R-squared: {r2}")
# print(f"Mean Squared Error: {mse}")
# # Statsmodels for detailed regression summary
# X_train_sm = sm.add_constant(X_train)  # Add a constant (intercept)
# model_sm = sm.OLS(y_train, X_train_sm).fit()
# print(model_sm.summary())  THIS REGRESSION AND VARIABLES   linear_regression_model.sav  WHERE THE MODEL IS SAVED GET MODEL FROM HERE   just load the file linear_regression_model.sav using pickle do not take csv file

import streamlit as st
import pickle
import numpy as np

# Load the saved model
model = pickle.load(open('linear_regression_model.sav', 'rb'))

st.title('Sales Prediction App')

# Input features
Income = st.number_input('Income', min_value=0.0)
Age = st.number_input('Age', min_value=0.0)
Education_Level = st.number_input('Education Level', min_value=0.0)
Monthly_Purchases = st.number_input('Monthly Purchases', min_value=0.0)


# Make prediction
if st.button('Predict Spending Score'):
    input_data = np.array([[Income, Age, Education_Level, Monthly_Purchases]])
    prediction = model.predict(input_data)[0]
    st.success(f'Predicted Spending Score: {prediction:.2f}')

